### ISSUE TITLE
Optional rounding

### ISSUE THREAD

**Issue by maticla** [TuckerMassad/react-animated-counter#3]
Remove or add an optional parameter to disable the rounding to nearest hundreth. For example, some cryptocurrency prices are unable to be presented fully.

It would be nice to have an optional parameter which would enable us to completely disable rounding.

**Comment by TuckerMassad** [comment]
I've added an optional `decimalPrecision` number parameter that is now available if you bump your package version to `1.6.0` or greater. Due to the cumbersome nature of subtracting floating point numbers in javascript, ex:

```
const myNumber = 10.2345 - 1.3241 // returns 8.910400000000001
```

I believe it will be more sustainable to have user-provided decimal precision. Let me know if you have any concerns or questions! @maticla Example usage below:

```
...
const [counterValue, setCounterValue] = useState(500.12345);
return ( 
  <AnimatedCounter
    value={counterValue}
    color="white"
    fontSize="40px"
    decimalPrecision={5}
  />
)
```

Result:

<img width="262" alt="Screen Shot 2023-11-01 at 5 02 13 PM" src="https://github.com/TuckerMassad/react-animated-counter/assets/22939424/dcb4093f-0064-459f-aca1-ac409ddc4d53">

**Comment by maticla** [comment]
Hey Tucker, that's awesome.  It's exactly what I needed. Thank you for this enhancement!

**Comment by TuckerMassad** [comment]
Wonderful - feel free to star the repo to support it's growth (it goes a long way!) and happy coding 😄  @maticla
